<?php

namespace MABI\EmailSupport\Testing;

include_once 'PHPUnit/Autoload.php';
include_once __DIR__ . '/../Mandrill.php';
include_once __DIR__ . '/../TokenTemplate.php';

class MandrillTest extends \PHPUnit_Framework_TestCase {

  protected function setUp()
  {
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function testSendEmail() {
    $template = new \MABI\EmailSupport\TokenTemplate('A man is still a child and I have so many questions', 'Acid Raindrops');
    $mandrill = new \MABI\EmailSupport\Mandrill("-gcII5trJDkpXO1OtzyHdA", "team@dashwith.me", 'Dash');
    $output = $mandrill->sendEmail("conord33@gmail.com", $template);
    $this->assertEquals("sent", $output->status);
  }

}