<?php

namespace MABI\EmailSupport\Testing;

include_once 'PHPUnit/Autoload.php';
include_once __DIR__ . '/../PHPCore.php';
include_once __DIR__ . '/../TokenTemplate.php';

class PHPCoreTest extends \PHPUnit_Framework_TestCase {

  protected function setUp()
  {
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function testSendEmail() {
    $template = new \MABI\EmailSupport\TokenTemplate('I never sleep cuz sleep is the cousin of death', 'N.Y. State of mind');
    $phpcore = new \MABI\EmailSupport\PHPCore("team@dashwith.me");
    $this->assertTrue($phpcore->sendEmail("conord33@gmail.com", $template));
  }

}